# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.define "iharileS"
  config.vm.hostname = "iharileS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.network "forwarded_port", guest: 80, host: 8082

  config.vm.provider "virtualbox" do |v|
    v.name = "iharileS"
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "file", source: "./confs/deployment", destination: "/tmp/deployment"
  config.vm.provision "file", source: "./confs/services", destination: "/tmp/services"
  config.vm.provision "file", source: "./confs/ingress/", destination: "/tmp/ingress"

  
  config.vm.provision "shell", privileged: true, path: "scripts/script.sh"



end