Vagrant.configure("2") do |config|
  # Server VM
  config.vm.define "abouhmadS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "abouhmadS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provision the Server using a script
    server.vm.provision "shell", path: "script/server.sh"
  end

  # Worker VM
  config.vm.define "abouhmadSW" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "abouhmadSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provision the Worker using a script
    worker.vm.provision "shell", path: "script/worker.sh"
  end
end
