# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  # config.vm.box = "gusztavvargadr/ubuntu-desktop-2404-lts"
  # config.vm.box_version = "2404.0.2409"

  config.vm.define "iharileS"
  config.vm.hostname = "iharileS"
  config.vm.network "private_network", ip: "192.168.56.115"
  # This is For UI of GitLab
  config.vm.network "forwarded_port", guest: 8888, host: 8080
  # This is for UI of ArgoCD
  config.vm.network "forwarded_port", guest: 8070, host: 8081



  config.vm.provider "virtualbox" do |v|
    v.name = "iharileS"
    v.memory = 8192
    v.cpus = 6
    
  end


  # Copy files to /home/vagrant
  
  config.vm.provision "file", source: "./confs/values.yml", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./confs/application.yml", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./script/install-gitlab.sh", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./script/install-argocd.sh", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./script/uninstall-k3s.sh", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./script/install-all.sh", destination: "/home/vagrant/"


  # Move files to root directory with elevated privileges
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    mkdir -p /confs /script
    mv /home/vagrant/values.yml /confs/values.yml
    mv /home/vagrant/application.yml /confs/application.yml

    mv /home/vagrant/install-gitlab.sh /script/install-gitlab.sh
    mv /home/vagrant/install-argocd.sh /script/install-argocd.sh
    mv /home/vagrant/uninstall-k3s.sh /script/uninstall-k3s.sh
    mv /home/vagrant/install-all.sh /script/install-all.sh
  SHELL



end